create database customer_behaviour;
use customer_behaviour;
select * from customer;

-- Q1. what is the total revenue generated by male vs female customers?
Select gender, SUM(purchase_amount) as revenue
FROM customer
Group by gender;

-- Q2. Which customers used a discount but still spent more than the avg purchase amount?
	SELECT customer_id, purchase_amount
    From customer
    WHERE discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS `Average Product Rating`
FROM 
    customer
GROUP BY 
    item_purchased
ORDER BY 
    AVG(review_rating) DESC
LIMIT 5;


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT shipping_type,
ROUND(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do Suscribed customers spend more? Compare average and total revenue between suscribers and non suscribers.
SELECT subscription_status,
      COUNT(customer_id) AS total_customers,
      ROUND(AVG(purchase_amount),2) AS avg_spend,
      ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
group by subscription_status
order by total_revenue,avg_spend DESC;      

-- Q6. Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into new, returning, and loyal based on their total number of previous purchase?
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

-- Q8. What are the top 3 most purchased products within each category?
with item_counts AS(
    SELECT category,
    item_purchased,
    COUNT(customer_id) AS total_orders,
    ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id)DESC) AS item_rank
FROM customer
group by category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;  

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
  SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?  
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer 
GROUP BY age_group
ORDER BY total_revenue desc;

    







